// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: encservice/v1/request_response.proto

package encservicev1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                []byte   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{0}
}
func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *HealthCheckResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type AddTxRequest struct {
	Txdata               []byte   `protobuf:"bytes,1,opt,name=txdata,proto3" json:"txdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTxRequest) Reset()         { *m = AddTxRequest{} }
func (m *AddTxRequest) String() string { return proto.CompactTextString(m) }
func (*AddTxRequest) ProtoMessage()    {}
func (*AddTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{1}
}
func (m *AddTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTxRequest.Unmarshal(m, b)
}
func (m *AddTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTxRequest.Marshal(b, m, deterministic)
}
func (m *AddTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTxRequest.Merge(m, src)
}
func (m *AddTxRequest) XXX_Size() int {
	return xxx_messageInfo_AddTxRequest.Size(m)
}
func (m *AddTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTxRequest proto.InternalMessageInfo

func (m *AddTxRequest) GetTxdata() []byte {
	if m != nil {
		return m.Txdata
	}
	return nil
}

type AddTxResponse struct {
	Txhash               []byte   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTxResponse) Reset()         { *m = AddTxResponse{} }
func (m *AddTxResponse) String() string { return proto.CompactTextString(m) }
func (*AddTxResponse) ProtoMessage()    {}
func (*AddTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{2}
}
func (m *AddTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTxResponse.Unmarshal(m, b)
}
func (m *AddTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTxResponse.Marshal(b, m, deterministic)
}
func (m *AddTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTxResponse.Merge(m, src)
}
func (m *AddTxResponse) XXX_Size() int {
	return xxx_messageInfo_AddTxResponse.Size(m)
}
func (m *AddTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTxResponse proto.InternalMessageInfo

func (m *AddTxResponse) GetTxhash() []byte {
	if m != nil {
		return m.Txhash
	}
	return nil
}

func (m *AddTxResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{3}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	Pending              uint64   `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	Queue                uint64   `protobuf:"varint,2,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{4}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetPending() uint64 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *StatusResponse) GetQueue() uint64 {
	if m != nil {
		return m.Queue
	}
	return 0
}

type ResetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{5}
}
func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

type ResetResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{6}
}
func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}
func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}
func (m *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(m, src)
}
func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}
func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PendingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingRequest) Reset()         { *m = PendingRequest{} }
func (m *PendingRequest) String() string { return proto.CompactTextString(m) }
func (*PendingRequest) ProtoMessage()    {}
func (*PendingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{7}
}
func (m *PendingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingRequest.Unmarshal(m, b)
}
func (m *PendingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingRequest.Marshal(b, m, deterministic)
}
func (m *PendingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingRequest.Merge(m, src)
}
func (m *PendingRequest) XXX_Size() int {
	return xxx_messageInfo_PendingRequest.Size(m)
}
func (m *PendingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PendingRequest proto.InternalMessageInfo

type PendingResponse struct {
	Txs                  [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingResponse) Reset()         { *m = PendingResponse{} }
func (m *PendingResponse) String() string { return proto.CompactTextString(m) }
func (*PendingResponse) ProtoMessage()    {}
func (*PendingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{8}
}
func (m *PendingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingResponse.Unmarshal(m, b)
}
func (m *PendingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingResponse.Marshal(b, m, deterministic)
}
func (m *PendingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingResponse.Merge(m, src)
}
func (m *PendingResponse) XXX_Size() int {
	return xxx_messageInfo_PendingResponse.Size(m)
}
func (m *PendingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PendingResponse proto.InternalMessageInfo

func (m *PendingResponse) GetTxs() [][]byte {
	if m != nil {
		return m.Txs
	}
	return nil
}

type BalanceRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlockNum             []byte   `protobuf:"bytes,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{9}
}
func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BalanceRequest) GetBlockNum() []byte {
	if m != nil {
		return m.BlockNum
	}
	return nil
}

type BalanceResponse struct {
	Balance              []byte   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{10}
}
func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

type NonceRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlockNum             []byte   `protobuf:"bytes,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceRequest) Reset()         { *m = NonceRequest{} }
func (m *NonceRequest) String() string { return proto.CompactTextString(m) }
func (*NonceRequest) ProtoMessage()    {}
func (*NonceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{11}
}
func (m *NonceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceRequest.Unmarshal(m, b)
}
func (m *NonceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceRequest.Marshal(b, m, deterministic)
}
func (m *NonceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceRequest.Merge(m, src)
}
func (m *NonceRequest) XXX_Size() int {
	return xxx_messageInfo_NonceRequest.Size(m)
}
func (m *NonceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonceRequest proto.InternalMessageInfo

func (m *NonceRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NonceRequest) GetBlockNum() []byte {
	if m != nil {
		return m.BlockNum
	}
	return nil
}

type NonceResponse struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceResponse) Reset()         { *m = NonceResponse{} }
func (m *NonceResponse) String() string { return proto.CompactTextString(m) }
func (*NonceResponse) ProtoMessage()    {}
func (*NonceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{12}
}
func (m *NonceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceResponse.Unmarshal(m, b)
}
func (m *NonceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceResponse.Marshal(b, m, deterministic)
}
func (m *NonceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceResponse.Merge(m, src)
}
func (m *NonceResponse) XXX_Size() int {
	return xxx_messageInfo_NonceResponse.Size(m)
}
func (m *NonceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NonceResponse proto.InternalMessageInfo

func (m *NonceResponse) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type LatestHeaderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestHeaderRequest) Reset()         { *m = LatestHeaderRequest{} }
func (m *LatestHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*LatestHeaderRequest) ProtoMessage()    {}
func (*LatestHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{13}
}
func (m *LatestHeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestHeaderRequest.Unmarshal(m, b)
}
func (m *LatestHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestHeaderRequest.Marshal(b, m, deterministic)
}
func (m *LatestHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestHeaderRequest.Merge(m, src)
}
func (m *LatestHeaderRequest) XXX_Size() int {
	return xxx_messageInfo_LatestHeaderRequest.Size(m)
}
func (m *LatestHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LatestHeaderRequest proto.InternalMessageInfo

type LatestHeaderResponse struct {
	BlockNum             []byte   `protobuf:"bytes,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	HeaderJson           []byte   `protobuf:"bytes,2,opt,name=header_json,json=headerJson,proto3" json:"header_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestHeaderResponse) Reset()         { *m = LatestHeaderResponse{} }
func (m *LatestHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*LatestHeaderResponse) ProtoMessage()    {}
func (*LatestHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{14}
}
func (m *LatestHeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestHeaderResponse.Unmarshal(m, b)
}
func (m *LatestHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestHeaderResponse.Marshal(b, m, deterministic)
}
func (m *LatestHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestHeaderResponse.Merge(m, src)
}
func (m *LatestHeaderResponse) XXX_Size() int {
	return xxx_messageInfo_LatestHeaderResponse.Size(m)
}
func (m *LatestHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestHeaderResponse proto.InternalMessageInfo

func (m *LatestHeaderResponse) GetBlockNum() []byte {
	if m != nil {
		return m.BlockNum
	}
	return nil
}

func (m *LatestHeaderResponse) GetHeaderJson() []byte {
	if m != nil {
		return m.HeaderJson
	}
	return nil
}

func init() {
	proto.RegisterType((*HealthCheckResponse)(nil), "encservice.v1.HealthCheckResponse")
	proto.RegisterType((*AddTxRequest)(nil), "encservice.v1.AddTxRequest")
	proto.RegisterType((*AddTxResponse)(nil), "encservice.v1.AddTxResponse")
	proto.RegisterType((*StatusRequest)(nil), "encservice.v1.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "encservice.v1.StatusResponse")
	proto.RegisterType((*ResetRequest)(nil), "encservice.v1.ResetRequest")
	proto.RegisterType((*ResetResponse)(nil), "encservice.v1.ResetResponse")
	proto.RegisterType((*PendingRequest)(nil), "encservice.v1.PendingRequest")
	proto.RegisterType((*PendingResponse)(nil), "encservice.v1.PendingResponse")
	proto.RegisterType((*BalanceRequest)(nil), "encservice.v1.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "encservice.v1.BalanceResponse")
	proto.RegisterType((*NonceRequest)(nil), "encservice.v1.NonceRequest")
	proto.RegisterType((*NonceResponse)(nil), "encservice.v1.NonceResponse")
	proto.RegisterType((*LatestHeaderRequest)(nil), "encservice.v1.LatestHeaderRequest")
	proto.RegisterType((*LatestHeaderResponse)(nil), "encservice.v1.LatestHeaderResponse")
}

func init() {
	proto.RegisterFile("encservice/v1/request_response.proto", fileDescriptor_ebcb1866dedad0bd)
}

var fileDescriptor_ebcb1866dedad0bd = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xa4, 0xf4, 0xcf, 0x60, 0x27, 0x25, 0x0d, 0x28, 0x94, 0x43, 0x23, 0x43, 0x51,
	0x24, 0xa4, 0x58, 0x16, 0xb7, 0x22, 0x24, 0x48, 0x15, 0xb5, 0x42, 0xa5, 0x8a, 0x4c, 0x15, 0x55,
	0xa8, 0x52, 0xb4, 0xb1, 0xa7, 0xb1, 0x89, 0xbd, 0x9b, 0x78, 0xd7, 0x91, 0x9f, 0x87, 0x23, 0x8f,
	0xc1, 0x91, 0xc7, 0xe0, 0xc8, 0x53, 0x20, 0x7b, 0x77, 0xe3, 0x9a, 0x2b, 0xb7, 0x7c, 0xb3, 0x33,
	0xdf, 0x6f, 0xf2, 0xc9, 0x03, 0xaf, 0x90, 0xfa, 0x1c, 0xd3, 0x4d, 0xe4, 0xa3, 0xb3, 0x71, 0x9d,
	0x14, 0xd7, 0x19, 0x72, 0x31, 0x4b, 0x91, 0xaf, 0x18, 0xe5, 0x38, 0x5c, 0xa5, 0x4c, 0xb0, 0x8e,
	0x55, 0x75, 0x0d, 0x37, 0xee, 0x71, 0x7f, 0xc1, 0xd8, 0x22, 0x46, 0xa7, 0x7c, 0x9c, 0x67, 0xf7,
	0xce, 0x7d, 0x84, 0x71, 0x30, 0x4b, 0x08, 0x5f, 0xca, 0x81, 0xe3, 0x93, 0x7f, 0x3b, 0x44, 0x94,
	0x20, 0x17, 0x24, 0x59, 0xc9, 0x06, 0xfb, 0x1c, 0x8e, 0x2e, 0x91, 0xc4, 0x22, 0x3c, 0x0f, 0xd1,
	0x5f, 0x7a, 0x0a, 0xd7, 0x79, 0x06, 0xbb, 0x5c, 0x10, 0x91, 0xf1, 0x9e, 0xd1, 0x37, 0x06, 0xfb,
	0x9e, 0x52, 0x9d, 0x2e, 0x3c, 0xc2, 0x34, 0x65, 0x69, 0xaf, 0xd1, 0x37, 0x06, 0xa6, 0x27, 0x85,
	0xfd, 0x1a, 0xcc, 0x8f, 0x41, 0x70, 0x93, 0x7b, 0x72, 0xeb, 0x62, 0x5a, 0xe4, 0x01, 0x11, 0xa4,
	0x9c, 0x36, 0x3d, 0xa5, 0xec, 0xf7, 0x60, 0xa9, 0xbe, 0x0a, 0x23, 0xf2, 0x90, 0xf0, 0xb0, 0x6a,
	0x2c, 0x54, 0x1d, 0x73, 0xa0, 0x31, 0x6d, 0xb0, 0xbe, 0x94, 0x6b, 0x28, 0x8e, 0xfd, 0x01, 0x5a,
	0xba, 0xa0, 0x0c, 0x7b, 0xb0, 0xb7, 0x42, 0x1a, 0x44, 0x74, 0x51, 0x3a, 0xee, 0x78, 0x5a, 0x16,
	0x96, 0xeb, 0x0c, 0x33, 0x2c, 0x2d, 0x77, 0x3c, 0x29, 0xec, 0x16, 0x98, 0x1e, 0x72, 0x14, 0xda,
	0xf1, 0x14, 0x2c, 0xa5, 0x95, 0xe1, 0x76, 0x13, 0xe3, 0xe1, 0x26, 0x87, 0xd0, 0x9a, 0x48, 0x5f,
	0x3d, 0xf8, 0x12, 0xda, 0xdb, 0x8a, 0x1a, 0x3d, 0x84, 0xa6, 0xc8, 0x8b, 0x00, 0x9b, 0x03, 0xd3,
	0x2b, 0x7e, 0xda, 0x17, 0xd0, 0x1a, 0x91, 0x98, 0x50, 0x1f, 0x75, 0x52, 0x3d, 0xd8, 0x23, 0x41,
	0x90, 0x22, 0xe7, 0x2a, 0x01, 0x2d, 0x3b, 0x2f, 0xe0, 0x60, 0x1e, 0x33, 0x7f, 0x39, 0xa3, 0x59,
	0xa2, 0xd2, 0xde, 0x2f, 0x0b, 0xd7, 0x59, 0x62, 0xbf, 0x81, 0xf6, 0xd6, 0xa8, 0xfa, 0xe7, 0x73,
	0x59, 0xd2, 0x4e, 0x4a, 0xda, 0x63, 0x30, 0xaf, 0xd9, 0xff, 0x33, 0x4f, 0xc1, 0x52, 0x36, 0x55,
	0x34, 0x94, 0x55, 0x3c, 0x29, 0xec, 0xa7, 0x70, 0x74, 0x45, 0x04, 0x72, 0x71, 0x89, 0x24, 0xc0,
	0x54, 0xe7, 0x73, 0x03, 0xdd, 0x7a, 0x59, 0x99, 0xd4, 0x90, 0x46, 0x1d, 0xd9, 0x39, 0x81, 0xc7,
	0x61, 0xd9, 0x3e, 0xfb, 0xc6, 0x19, 0x55, 0x1b, 0x81, 0x2c, 0x7d, 0xe2, 0x8c, 0x8e, 0x7e, 0x1a,
	0xf0, 0xc4, 0x67, 0xc9, 0xb0, 0x76, 0x16, 0xa3, 0xae, 0x82, 0x6a, 0xc8, 0xa4, 0xf8, 0xd2, 0x27,
	0xc6, 0xd7, 0xd1, 0x22, 0x12, 0x61, 0x36, 0x1f, 0xfa, 0x2c, 0x71, 0xf2, 0x0c, 0xd7, 0x11, 0xa1,
	0x57, 0x99, 0x83, 0xd4, 0x17, 0xf9, 0x8a, 0xb1, 0x58, 0x1e, 0x89, 0xcf, 0x62, 0xa7, 0x76, 0x8b,
	0xef, 0x2a, 0xb5, 0x71, 0xbf, 0x37, 0x9a, 0xe3, 0xdb, 0xdb, 0x1f, 0x0d, 0x6b, 0x5c, 0x11, 0xa7,
	0xee, 0xaf, 0x87, 0xfa, 0x6e, 0xea, 0xfe, 0x6e, 0x3c, 0xaf, 0xe9, 0xbb, 0x8b, 0xc9, 0xe8, 0x33,
	0x0a, 0x52, 0x1c, 0xc1, 0x9f, 0x46, 0xab, 0x7a, 0x3b, 0x3b, 0x9b, 0xba, 0xf3, 0xdd, 0x92, 0xfb,
	0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0xe0, 0xd3, 0x11, 0x03, 0x04, 0x00, 0x00,
}
