// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: encservice/v1/request_response.proto

package encservicev1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                []byte   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{0}
}
func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *HealthCheckResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type AddTxRequest struct {
	Txdata               []byte   `protobuf:"bytes,1,opt,name=txdata,proto3" json:"txdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTxRequest) Reset()         { *m = AddTxRequest{} }
func (m *AddTxRequest) String() string { return proto.CompactTextString(m) }
func (*AddTxRequest) ProtoMessage()    {}
func (*AddTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{1}
}
func (m *AddTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTxRequest.Unmarshal(m, b)
}
func (m *AddTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTxRequest.Marshal(b, m, deterministic)
}
func (m *AddTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTxRequest.Merge(m, src)
}
func (m *AddTxRequest) XXX_Size() int {
	return xxx_messageInfo_AddTxRequest.Size(m)
}
func (m *AddTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTxRequest proto.InternalMessageInfo

func (m *AddTxRequest) GetTxdata() []byte {
	if m != nil {
		return m.Txdata
	}
	return nil
}

type AddTxResponse struct {
	Txhash               []byte   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTxResponse) Reset()         { *m = AddTxResponse{} }
func (m *AddTxResponse) String() string { return proto.CompactTextString(m) }
func (*AddTxResponse) ProtoMessage()    {}
func (*AddTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{2}
}
func (m *AddTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTxResponse.Unmarshal(m, b)
}
func (m *AddTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTxResponse.Marshal(b, m, deterministic)
}
func (m *AddTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTxResponse.Merge(m, src)
}
func (m *AddTxResponse) XXX_Size() int {
	return xxx_messageInfo_AddTxResponse.Size(m)
}
func (m *AddTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTxResponse proto.InternalMessageInfo

func (m *AddTxResponse) GetTxhash() []byte {
	if m != nil {
		return m.Txhash
	}
	return nil
}

func (m *AddTxResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{3}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	Pending              uint64   `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	Queue                uint64   `protobuf:"varint,2,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{4}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetPending() uint64 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *StatusResponse) GetQueue() uint64 {
	if m != nil {
		return m.Queue
	}
	return 0
}

type ResetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{5}
}
func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

type ResetResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{6}
}
func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}
func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}
func (m *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(m, src)
}
func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}
func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PendingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingRequest) Reset()         { *m = PendingRequest{} }
func (m *PendingRequest) String() string { return proto.CompactTextString(m) }
func (*PendingRequest) ProtoMessage()    {}
func (*PendingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{7}
}
func (m *PendingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingRequest.Unmarshal(m, b)
}
func (m *PendingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingRequest.Marshal(b, m, deterministic)
}
func (m *PendingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingRequest.Merge(m, src)
}
func (m *PendingRequest) XXX_Size() int {
	return xxx_messageInfo_PendingRequest.Size(m)
}
func (m *PendingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PendingRequest proto.InternalMessageInfo

type PendingResponse struct {
	Txs                  [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingResponse) Reset()         { *m = PendingResponse{} }
func (m *PendingResponse) String() string { return proto.CompactTextString(m) }
func (*PendingResponse) ProtoMessage()    {}
func (*PendingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebcb1866dedad0bd, []int{8}
}
func (m *PendingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingResponse.Unmarshal(m, b)
}
func (m *PendingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingResponse.Marshal(b, m, deterministic)
}
func (m *PendingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingResponse.Merge(m, src)
}
func (m *PendingResponse) XXX_Size() int {
	return xxx_messageInfo_PendingResponse.Size(m)
}
func (m *PendingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PendingResponse proto.InternalMessageInfo

func (m *PendingResponse) GetTxs() [][]byte {
	if m != nil {
		return m.Txs
	}
	return nil
}

func init() {
	proto.RegisterType((*HealthCheckResponse)(nil), "encservice.v1.HealthCheckResponse")
	proto.RegisterType((*AddTxRequest)(nil), "encservice.v1.AddTxRequest")
	proto.RegisterType((*AddTxResponse)(nil), "encservice.v1.AddTxResponse")
	proto.RegisterType((*StatusRequest)(nil), "encservice.v1.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "encservice.v1.StatusResponse")
	proto.RegisterType((*ResetRequest)(nil), "encservice.v1.ResetRequest")
	proto.RegisterType((*ResetResponse)(nil), "encservice.v1.ResetResponse")
	proto.RegisterType((*PendingRequest)(nil), "encservice.v1.PendingRequest")
	proto.RegisterType((*PendingResponse)(nil), "encservice.v1.PendingResponse")
}

func init() {
	proto.RegisterFile("encservice/v1/request_response.proto", fileDescriptor_ebcb1866dedad0bd)
}

var fileDescriptor_ebcb1866dedad0bd = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcd, 0xae, 0x93, 0x40,
	0x14, 0xc7, 0x03, 0xbd, 0x5e, 0x75, 0x02, 0xdc, 0x6b, 0xbd, 0x31, 0xb5, 0x1b, 0x1b, 0xfc, 0x48,
	0x57, 0x10, 0xe2, 0xae, 0xc6, 0x44, 0x69, 0x1a, 0x5d, 0x68, 0x42, 0x46, 0xd3, 0x34, 0xa6, 0x49,
	0x33, 0x85, 0x53, 0x20, 0x05, 0x86, 0x32, 0x33, 0x84, 0xe7, 0x71, 0xe9, 0x63, 0xb8, 0xf4, 0x31,
	0x5c, 0xfa, 0x14, 0x06, 0x18, 0x4a, 0xb9, 0x3b, 0x7e, 0x33, 0xff, 0x8f, 0x13, 0xce, 0xa0, 0x57,
	0x90, 0xf9, 0x0c, 0x8a, 0x32, 0xf6, 0xc1, 0x2e, 0x1d, 0xbb, 0x80, 0x93, 0x00, 0xc6, 0x77, 0x05,
	0xb0, 0x9c, 0x66, 0x0c, 0xac, 0xbc, 0xa0, 0x9c, 0x8e, 0xf5, 0x5e, 0x65, 0x95, 0xce, 0x74, 0x16,
	0x52, 0x1a, 0x26, 0x60, 0x37, 0x97, 0x7b, 0x71, 0xb0, 0x0f, 0x31, 0x24, 0xc1, 0x2e, 0x25, 0xec,
	0xd8, 0x1a, 0xa6, 0x2f, 0xee, 0x2b, 0x78, 0x9c, 0x02, 0xe3, 0x24, 0xcd, 0x5b, 0x81, 0xb9, 0x44,
	0x4f, 0x3f, 0x03, 0x49, 0x78, 0xb4, 0x8c, 0xc0, 0x3f, 0x62, 0x59, 0x37, 0x7e, 0x86, 0xae, 0x19,
	0x27, 0x5c, 0xb0, 0x89, 0x32, 0x53, 0xe6, 0x8f, 0xb0, 0xa4, 0xf1, 0x1d, 0x7a, 0x00, 0x45, 0x41,
	0x8b, 0x89, 0x3a, 0x53, 0xe6, 0x1a, 0x6e, 0xc1, 0x7c, 0x83, 0xb4, 0x8f, 0x41, 0xf0, 0xbd, 0xc2,
	0xed, 0xd4, 0xb5, 0x9b, 0x57, 0x01, 0xe1, 0xa4, 0x71, 0x6b, 0x58, 0x92, 0xf9, 0x1e, 0xe9, 0x52,
	0xd7, 0xd7, 0xf0, 0x2a, 0x22, 0x2c, 0xea, 0x85, 0x35, 0x0d, 0x6b, 0x1e, 0x77, 0x35, 0x37, 0x48,
	0xff, 0xd6, 0x8c, 0x21, 0x7b, 0xcc, 0x0f, 0xc8, 0xe8, 0x0e, 0x64, 0xe0, 0x04, 0x3d, 0xcc, 0x21,
	0x0b, 0xe2, 0x2c, 0x6c, 0x12, 0xaf, 0x70, 0x87, 0x75, 0xe4, 0x49, 0x80, 0x80, 0x26, 0xf2, 0x0a,
	0xb7, 0x60, 0x1a, 0x48, 0xc3, 0xc0, 0x80, 0x77, 0x89, 0xaf, 0x91, 0x2e, 0x59, 0x06, 0x9e, 0x27,
	0x51, 0x2e, 0x27, 0xb9, 0x45, 0x86, 0xd7, 0xe6, 0x76, 0xc6, 0x97, 0xe8, 0xe6, 0x7c, 0x22, 0xad,
	0xb7, 0x68, 0xc4, 0xab, 0xfa, 0x07, 0x8e, 0xe6, 0x1a, 0xae, 0x3f, 0xdd, 0xdf, 0x0a, 0x7a, 0xe2,
	0xd3, 0xd4, 0x1a, 0x6c, 0xd1, 0xbd, 0x93, 0x19, 0x9d, 0xd1, 0xab, 0x17, 0xe3, 0x29, 0x3f, 0xdc,
	0x30, 0xe6, 0x91, 0xd8, 0x5b, 0x3e, 0x4d, 0xed, 0x4a, 0xc0, 0x29, 0x26, 0xd9, 0x17, 0x61, 0x43,
	0xe6, 0xf3, 0x2a, 0xa7, 0x34, 0x69, 0x77, 0xea, 0xd3, 0xc4, 0x1e, 0x3c, 0x9d, 0x77, 0x3d, 0x95,
	0xce, 0x4f, 0x75, 0xb4, 0xda, 0x6c, 0x7e, 0xa9, 0xfa, 0xaa, 0x6f, 0x5c, 0x3b, 0x7f, 0x2e, 0x79,
	0xbb, 0x76, 0xfe, 0xaa, 0xcf, 0x07, 0xbc, 0xfd, 0xe4, 0xb9, 0x5f, 0x81, 0x93, 0x7a, 0x67, 0xff,
	0x54, 0xa3, 0xbf, 0x5b, 0x2c, 0xd6, 0xce, 0xfe, 0xba, 0xe9, 0x7d, 0xfb, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0x93, 0xf4, 0x8b, 0x29, 0xb2, 0x02, 0x00, 0x00,
}
